exps:
  - name: exp1
    base_model: mobilenet
    output_format: distribution
    batch_size: 64
    layers:
      - layer: brightness
        args:
          - 0.1
      - layer: contrast
        args:
          - 0.1
  - name: exp2
    base_model: mobilenet
    output_format: distribution
    batch_size: 64
    layers:
      - layer: crop
      - layer: flip